# SPDX-FileCopyrightText: Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

name: Daily

on:
  push:

  pull_request:
  workflow_dispatch:
  # 8am UTC is 12am PST, 1am PDT
  schedule:
    - cron: '0 8 * * *'

jobs:
  checks:
    runs-on: devcloud
    env:
      CXX: icpx
      CC: icx
    steps:
    - uses: actions/checkout@v4
    - name: Apt installs
      run: |
        sudo apt update
        sudo apt install -y clang-format clang-tidy uncrustify cppcheck iwyu
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install pre-commit
    - run: pre-commit run --all-files
    - name: Build & Run
      run: srun -p pvc-shared -w idc-beta-batch-pvc-node-12 scripts/daily.sh
