# SPDX-FileCopyrightText: Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

name: Docker
permissions: read-all

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run_precommit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Run checkers
        run: |
          pip install pre-commit
          pre-commit run --all
          
  run_examples:
    name: Build and run examples
    runs-on: ubuntu-latest
    container:
      image: intel/oneapi:latest
      env:
        CXX: icpx
        CC: icx
      volumes:
        - ${{ github.workspace }}:/src
    steps:
      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Build examples
        run: |
          cmake -B build
          cmake --build build -j
      - name: Run examples
        run: |
          mpirun -n 3 ./build/src/example1
          mpirun -n 3 ./build/src/example2
          mpirun -n 3 ./build/src/example3
          mpirun -n 3 ./build/src/example4
          mpirun -n 3 ./build/src/example5
          mpirun -n 3 ./build/src/example6
