# SPDX-FileCopyrightText: Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

name: Docker

on:
  push:
  pull_request:
  workflow_dispatch:
  # 8am UTC is 12am PST, 1am PDT
  schedule:
  - cron: '0 8 * * *'

jobs:
  run_precommit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
  run_examples:
    name: Build and run examples
    runs-on: ubuntu-latest
    container:
      image: intel/oneapi:latest
      env:
        CXX: icpx
        CC: icx
      volumes:
        - ${{ github.workspace }}:/src
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
      - name: Build examples
        run: |
          cmake -B build
          cmake --build build -j
      - name: Run examples
        run: |
          mpirun -n 2 ./build/src/example1
          mpirun -n 2 ./build/src/example2
          mpirun -n 2 ./build/src/example3
